// This file was generated by running:
// flutterfire configure
//
// If you encounter issues with authentication (sign-in, registration failing),
// it's likely because this file contains stub values.
//
// To fix this:
// 1. Install FlutterFire CLI: dart pub global activate flutterfire_cli
// 2. Set up a Firebase project at https://console.firebase.google.com/
// 3. Enable Email/Password authentication in Firebase Console
// 4. Run: flutterfire configure
// 5. Replace this file with the generated one
//
// See FIREBASE_SETUP_GUIDE.md for detailed instructions.

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl2...',  // Replace with your web API key from Firebase Console
    appId: '1:123456789:web:abcdef...',
    messagingSenderId: '123456789',
    projectId: 'your-project-id',
    authDomain: 'your-project-id.firebaseapp.com',
    databaseURL: 'https://your-project-id.firebaseio.com',
    storageBucket: 'your-project-id.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl2...',  // Replace with your Android API key
    appId: '1:123456789:android:abcdef...',
    messagingSenderId: '123456789',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl2...',  // Replace with your iOS API key
    appId: '1:123456789:ios:abcdef...',
    messagingSenderId: '123456789',
    projectId: 'your-project-id',
    iosBundleId: 'com.example.sociefy',
    storageBucket: 'your-project-id.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl2...',  // Replace with your macOS API key
    appId: '1:123456789:ios:abcdef...',
    messagingSenderId: '123456789',
    projectId: 'your-project-id',
    iosBundleId: 'com.example.sociefy',
    storageBucket: 'your-project-id.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl2...',  // Replace with your Windows API key
    appId: '1:123456789:windows:abcdef...',
    messagingSenderId: '123456789',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
  );
}
